### ISSUE TITLE
能不能同步更新一下code.sh和task_before.sh

### ISSUE THREAD

**Issue by uminoai** [Oreomeow/VIP#12]
看了下目前QINGLONG文件夹里面只有config.sh，能不能也更新下code.sh和task_before.sh呢，因为不经常上TG，想拉库自动更新，谢谢！

**Comment by synoman** [comment]
这个问题我已经搞定了，自己修改了作者的update.sh，使用sed 命令把自己的一些变量值加进去，这样就省去了每次都手动修改的烦恼。（作者的UPDATE.SH写的真是太好了）, 然后禁用自带的update.sh，自己在青龙任务里面添加一下魔改的UPDATE就行了
